# Generated by Django 4.2.3 on 2023-07-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
