# Generated by Django 4.2.3 on 2023-07-22 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name_plural": "cities"},
        ),
    ]
