# Generated by Django 4.2.3 on 2023-07-21 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0001_initial"),
        ("tickets", "0003_ticket_unique_row_and_seat"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_row_and_seat",
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("row", "seat", "flight")},
        ),
    ]
